spring:
  security:
    user:
      name: usr
      password: pwd
    oauth2:
      client:
        registration:
          github:
            clientId: abc
            clientSecret: xyz

my:
  https:
    enabled: true
